version: '3'
services:
  backend:
    image: nathaniel2662000/flask-app
    ports:
      -"5000:5000"
    environment:
      - MYSQL_HOST: "mysql"
      - MYSQL_USER: "admin"
      - MYSQL_DATABASE: "myDb"
      - MYSQL_PASSWORD: "admin"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      -"3306:3306"
    environment:
      - MYSQL_USER: "admin"
      - MYSQL_DATABASE: "myDb"
      - MYSQL_PASSWORD: "admin"
      - MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

